### ISSUE TITLE
Wordpress example not working with OpenShift

### ISSUE THREAD

**Issue by cdrage** [projectatomic/nulecule-library#39]
Getting this error within OpenShift:

```
Running mysql_install_db ...
mkdir: cannot create directory '/var/lib/mysql/mysql': Permission denied
Fatal error Can't create database directory '/var/lib/mysql/mysql'

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
```

with the MariaDB image. Due to this error, the wpfrontend container does not start.

Ping @goern ? I think you were the last one that worked on this?

**Comment by dustymabe** [comment]
@cdrage I updated the mariadb atomicapp to work on openshift. Did you build the example from scratch or pull it from the registry? If pulled from registry it may need to be rebuilt.

**Comment by cdrage** [comment]
@dustymabe pulling and building from nulecule-library. just checked past commits to here and I don't see a fix to mariadb?

**Comment by dustymabe** [comment]
@cdrage the fix was actually to the mariadb base container from the CentOS dockerfiles repo. can you clean up that container on your system and re-pull from docker hub and test again?

**Comment by cdrage** [comment]
Works :+1: closing this issue
